# Generated by Django 4.2 on 2024-04-27 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0024_remove_station_height_station_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='rainfall_3h',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بارندگی 3 ساعت اخیر'),
        ),
        migrations.AlterField(
            model_name='station',
            name='year_rainfall',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بارندگی سال'),
        ),
    ]
