# Generated by Django 4.2 on 2024-05-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0025_station_rainfall_3h_alter_station_year_rainfall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_rainfall_date_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ثبت بارندگی اخیر'),
        ),
    ]
